### PR TITLE
Update axios and prepare for a 0.1.0 release

### PR DESCRIPTION
**Pull request by scsmith**

### CODE REVIEW

**Comment by scsmith** [comment]
@sakgoyal would you take a look at this and see if it satisfies your needs? I don't think we really want to update typescript or make any changes to the automatically generates files at this point. However, we'll review those options once this is live.

**Comment by sakgoyal** [comment]
Axios needs to be as updated as possible. The older versions have security vulnerabilities. 

I don't really care about the other dependencies as it doesn't really affect anything else.

**Comment by scsmith** [comment]
> Axios needs to be as updated as possible. The older versions have security vulnerabilities.

This should allow any version of axios < 2.0 whilst not forcing anyone to use a specific version of 1.x. We'll try and get this published today.

**Comment by sakgoyal** [comment]
Oh I missed the "^" in the package version. Perfect. Thank you

**Pull request merged**
